import type { Metadata, Viewport } from "next";
import "./globals.css";
import StyleProvider from "@/components/StyleProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyleProvider>
        <body className="overflow-hidden">{children}</body>
      </StyleProvider>
    </html>
  );
}
